### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by MadushaS** [UOKCS-19/UOKCS-19.github.io#16]
In the readme, there is an unnecessary empty Contribution title near the bottom. Remove it

Instead of the Text link use,
![link](https://img.shields.io/badge/Live%20Preview-online-brightgreen)

for that use

```markdown
![link](https://img.shields.io/badge/Live%20Preview-online-brightgreen)
```

**Comment by the-amazing-atharva** [comment]
Hi!
I would like to contribute to this issue!

**Comment by MadushaS** [comment]
forget the above 2 pull requests. (not related to this)

**Comment by MadushaS** [comment]
@YSanj98 always comment below the issue (like @the-amazing-atharva ) that you would like to contribute before starting going on full dev mode. So that I can assign requested people and others can clearly know that this issue is handled by you.

**Comment by AyishaIlyas** [comment]
done
